# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menuShift.ui'
#
# Created: Sun Jul 29 16:14:10 2018
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 533)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tableWidgetShift = QtGui.QTableWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidgetShift.sizePolicy().hasHeightForWidth())
        self.tableWidgetShift.setSizePolicy(sizePolicy)
        self.tableWidgetShift.setMinimumSize(QtCore.QSize(300, 0))
        self.tableWidgetShift.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidgetShift.setAlternatingRowColors(True)
        self.tableWidgetShift.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidgetShift.setObjectName(_fromUtf8("tableWidgetShift"))
        self.tableWidgetShift.setColumnCount(2)
        self.tableWidgetShift.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetShift.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetShift.setHorizontalHeaderItem(1, item)
        self.gridLayout.addWidget(self.tableWidgetShift, 3, 0, 1, 1)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.lineEditKodeShift = QtGui.QLineEdit(self.centralwidget)
        self.lineEditKodeShift.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEditKodeShift.setObjectName(_fromUtf8("lineEditKodeShift"))
        self.gridLayout_3.addWidget(self.lineEditKodeShift, 0, 1, 1, 1)
        self.lineEditDept = QtGui.QLineEdit(self.centralwidget)
        self.lineEditDept.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEditDept.setObjectName(_fromUtf8("lineEditDept"))
        self.gridLayout_3.addWidget(self.lineEditDept, 0, 3, 1, 1)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_3.addWidget(self.label_3, 0, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 4, 1, 1)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.pushButtonInput = QtGui.QPushButton(self.centralwidget)
        self.pushButtonInput.setObjectName(_fromUtf8("pushButtonInput"))
        self.gridLayout_4.addWidget(self.pushButtonInput, 1, 0, 1, 1)
        self.timeEditPulang = QtGui.QTimeEdit(self.centralwidget)
        self.timeEditPulang.setObjectName(_fromUtf8("timeEditPulang"))
        self.gridLayout_4.addWidget(self.timeEditPulang, 1, 2, 1, 1)
        self.comboBoxHari = QtGui.QComboBox(self.centralwidget)
        self.comboBoxHari.setMaximumSize(QtCore.QSize(100, 16777215))
        self.comboBoxHari.setObjectName(_fromUtf8("comboBoxHari"))
        self.comboBoxHari.addItem(_fromUtf8(""))
        self.comboBoxHari.addItem(_fromUtf8(""))
        self.comboBoxHari.addItem(_fromUtf8(""))
        self.comboBoxHari.addItem(_fromUtf8(""))
        self.comboBoxHari.addItem(_fromUtf8(""))
        self.comboBoxHari.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.comboBoxHari, 0, 0, 1, 1)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_4.addWidget(self.label, 0, 1, 1, 1)
        self.timeEditDatang = QtGui.QTimeEdit(self.centralwidget)
        self.timeEditDatang.setObjectName(_fromUtf8("timeEditDatang"))
        self.gridLayout_4.addWidget(self.timeEditDatang, 0, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_4.addWidget(self.label_4, 1, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 0, 3, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_4, 1, 0, 1, 5)
        self.gridLayout.addLayout(self.gridLayout_3, 0, 0, 1, 3)
        self.tableWidget = QtGui.QTableWidget(self.centralwidget)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(6)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.gridLayout.addWidget(self.tableWidget, 3, 1, 1, 2)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionExport_Excel = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/DESIGN/icon/32x32/file_extension_xls.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExport_Excel.setIcon(icon)
        self.actionExport_Excel.setObjectName(_fromUtf8("actionExport_Excel"))
        self.actionShow_Data = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/DESIGN/icon/32x32/application_form_magnify.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionShow_Data.setIcon(icon1)
        self.actionShow_Data.setObjectName(_fromUtf8("actionShow_Data"))
        self.actionKeluar = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/DESIGN/icon/32x32/door_in.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionKeluar.setIcon(icon2)
        self.actionKeluar.setObjectName(_fromUtf8("actionKeluar"))
        self.actionGrafik = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/DESIGN/icon/32x32/chart_bar.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGrafik.setIcon(icon3)
        self.actionGrafik.setObjectName(_fromUtf8("actionGrafik"))
        self.actionTambah_User = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/DESIGN/icon/32x32/add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTambah_User.setIcon(icon4)
        self.actionTambah_User.setObjectName(_fromUtf8("actionTambah_User"))
        self.actionHapus = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/DESIGN/icon/32x32/delete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHapus.setIcon(icon5)
        self.actionHapus.setObjectName(_fromUtf8("actionHapus"))
        self.actionReport_Periode = QtGui.QAction(MainWindow)
        self.actionReport_Periode.setIcon(icon3)
        self.actionReport_Periode.setObjectName(_fromUtf8("actionReport_Periode"))
        self.actionBatal = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/DESIGN/icon/32x32/cancel.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBatal.setIcon(icon6)
        self.actionBatal.setObjectName(_fromUtf8("actionBatal"))
        self.toolBar.addAction(self.actionTambah_User)
        self.toolBar.addAction(self.actionHapus)
        self.toolBar.addAction(self.actionBatal)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        item = self.tableWidgetShift.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Kode Shift", None))
        item = self.tableWidgetShift.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Departemen", None))
        self.label_2.setText(_translate("MainWindow", "Kode Shift", None))
        self.label_3.setText(_translate("MainWindow", "Departemen", None))
        self.pushButtonInput.setText(_translate("MainWindow", "Input", None))
        self.timeEditPulang.setDisplayFormat(_translate("MainWindow", "HH:mm", None))
        self.comboBoxHari.setItemText(0, _translate("MainWindow", "Senin", None))
        self.comboBoxHari.setItemText(1, _translate("MainWindow", "Selasa", None))
        self.comboBoxHari.setItemText(2, _translate("MainWindow", "Rabu", None))
        self.comboBoxHari.setItemText(3, _translate("MainWindow", "Kamis", None))
        self.comboBoxHari.setItemText(4, _translate("MainWindow", "Jum\'at", None))
        self.comboBoxHari.setItemText(5, _translate("MainWindow", "Sabtu", None))
        self.label.setText(_translate("MainWindow", "Jam Datang :", None))
        self.timeEditDatang.setDisplayFormat(_translate("MainWindow", "HH:mm", None))
        self.label_4.setText(_translate("MainWindow", "Jam Pulang :", None))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Senin", None))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Selasa", None))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Rabu", None))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Kamis", None))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "Jum\'at", None))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "Sabtu", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Jam Datang", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Jam Pulang", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.actionExport_Excel.setText(_translate("MainWindow", "Export Excel", None))
        self.actionShow_Data.setText(_translate("MainWindow", "Show Data", None))
        self.actionKeluar.setText(_translate("MainWindow", "Keluar", None))
        self.actionGrafik.setText(_translate("MainWindow", "Grafik", None))
        self.actionTambah_User.setText(_translate("MainWindow", "Tambah User", None))
        self.actionHapus.setText(_translate("MainWindow", "Hapus", None))
        self.actionReport_Periode.setText(_translate("MainWindow", "Report Periode", None))
        self.actionBatal.setText(_translate("MainWindow", "Batal", None))

import icon_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

